Complex topic whitelisting from file
gojek/vernemq pull request #41
Opened 2024-02-06 17:35 UTC by VivekPipaliya23

## Proposed Changes
Currently the complex topic is added via the vmq-admin CLI and it is stored in redis.
This PR adds complex topics using a file and updates the complex topic trie in give interval.
Removes the implementations of storing topics in redis.

## Types of Changes

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

2024-02-12 06:20 UTC, dhruvjain99 requested changes

2024-02-13 07:20 UTC, VivekPipaliya23 commented on apps/vmq_enhanced_auth/src/vmq_enhanced_auth.erl
> +    ets:match_delete(T, {'_', 2, '_'}).
we are adding label at the end as third argument.
`t(read, token, Topic, Label) -> {vmq_enhanced_auth_acl_read_token, {Topic, 1, Label}};`
so at the time of `del_aged_entries` it needs to match third argument.

2024-02-13 10:29 UTC, VivekPipaliya23 commented on apps/vmq_server/priv/vmq_server.schema
> +%% @doc Set the path to an complex access control list file.
Updated

2024-02-13 10:30 UTC, VivekPipaliya23 commented on apps/vmq_server/priv/vmq_server.schema
> +{mapping, "vmq_trie.acl_file", "vmq_server.file", [
Updated to `complex_trie_file`

2024-02-13 10:30 UTC, VivekPipaliya23 commented on apps/vmq_server/priv/vmq_server.schema
> +{mapping, "vmq_trie.acl_reload_interval", "vmq_server.interval", [
Updated to `complex_trie_reload_interval`

2024-02-13 10:30 UTC, VivekPipaliya23 commented on apps/vmq_server/priv/vmq_server.schema
> +%% @doc set the acl reload interval in seconds, the value 0 disables
Updated

2024-02-13 10:31 UTC, VivekPipaliya23 commented on apps/vmq_server/src/vmq_reg_redis_trie.erl
> +            update_complex_topics(TopicList);
Updated the fn name

2024-02-13 10:32 UTC, VivekPipaliya23 commented on apps/vmq_server/src/vmq_reg_redis_trie.erl
> +            Topics = create_list(Lines),
Removed the create_list fn.

2024-02-13 10:32 UTC, VivekPipaliya23 commented on apps/vmq_server/src/vmq_server_cli.erl
>      vmq_reg_redis_trie_show_wildcard_topics_cmd(),
Updated to `vmq_trie_show_complex_topics_cmd`

2024-02-13 10:35 UTC, VivekPipaliya23 commented on apps/vmq_server/src/vmq_reg_redis_trie.erl
> +load_from_file(File) ->
`parse_topic_list` should only return valid topics

2024-02-13 10:36 UTC, VivekPipaliya23 commented on apps/vmq_server/src/vmq_reg_redis_trie.erl
> +            TopicList = parse_topic_list(Topics),
Updated `parse_topic_list` to return list of only valid topics.

2024-02-15 04:56 UTC, VivekPipaliya23 commented on apps/vmq_server/src/vmq_reg_redis_trie.erl
> +            TopicList = parse_topic_list(Topics),
Added spec for `parse_topic_list`.

2024-02-15 04:57 UTC, VivekPipaliya23 commented on apps/vmq_server/src/vmq_reg_redis_trie.erl
> +                        false -> Acc
Added log

2024-02-15 04:57 UTC, VivekPipaliya23 commented on apps/vmq_server/src/vmq_reg_redis_trie.erl
> +                _ ->
Added log

2024-02-19 14:03 UTC, dhruvjain99 approved these changes

2024-02-19 14:04 UTC, merged