feat: add topic level sampling with on_deliver event
gojek/vernemq pull request #44
Opened 2024-02-09 05:49 UTC by VivekPipaliya23

## Proposed Changes

This MR adds the capability to enable/disable hook events based on acl_name for on_deliver.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

- [x] I have read the `CODE_OF_CONDUCT.md` document
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

2024-02-12 06:21 UTC, dhruvjain99 requested changes

2024-02-12 18:29 UTC, VivekPipaliya23 commented on apps/vmq_events_sidecar/priv/vmq_events_sidecar.schema
>  %% @doc Configure the sampling for on_deliver events based on user names
updated with `...on_deliver events based on ACL names`

2024-02-12 18:31 UTC, VivekPipaliya23 commented on apps/vmq_events_sidecar/src/vmq_events_sidecar_cli.erl
>              (_, [{hook, on_publish}, {percentage, P}], [{acl_name, ACL}]) ->
Added `sampling_acl_name_flagspec()` to `KeySpecs` in both `enable` and `disable` commands.

2024-02-14 08:51 UTC, dhruvjain99 submitted a review, later dismissed

2024-02-19 04:01 UTC, dhruvjain99 approved these changes

2024-02-19 04:02 UTC, merged